# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Bye Bye Birdie
author: 

sphinx:
  config:
    html_show_copyright: false
    html_theme_options:
      use_fullscreen_button: false
      use_download_button: false

parse:
   myst_url_schemes: [mailto, http, https, t]
